# Generated by Django 4.2.5 on 2023-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
