# Generated by Django 4.2.5 on 2023-10-03 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_promotion_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['label'], 'verbose_name': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['label'], 'verbose_name': 'Catégorie'},
        ),
        migrations.AlterField(
            model_name='article',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=100, unique=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(verbose_name='Date de fin de promotion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pourcentage de remise'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(verbose_name='Date début de promotion'),
        ),
    ]
