# Generated by Django 4.2.5 on 2023-09-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_article_description_alter_category_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.administrator'),
        ),
    ]
