# Generated by Django 4.2.5 on 2023-09-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_article_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.administrator'),
        ),
    ]
